spring:
  datasource:
    url: jdbc:mysql://localhost:3306/future_wiki
    username: root
    password: bahareh8529
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "FutureWikiSuperSecretKeyForJwtAuthentication2026VeryLongKey123456"
  expiration: 86400000